sudo apt-get install g++ 
sudo apt-get install binutils 
sudo apt-get install libc6-dev-i386
sudo apt-get install xorriso
sudo apt-get install make
sudo apt-get install mtools
sudo apt-get install VirtualBox 
sudo apt-get install grub-legacy
sudo apt-get install perl